travlounge/Travlounge/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from IT_ADMIN import views
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path('token/', views.preview, name='tocken'),
    path('admin/', admin.site.urls),
    
    path('summernote/', include('django_summernote.urls')),
    path('firebase-messaging-sw.js', (TemplateView.as_view(template_name="firebase-messaging-sw.js",
         content_type='application/javascript')), name='sw.js'),
]

admin.site.site_title = 'Travlounge'
admin.site.index_title = 'Manage facilities'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

travlounge/CORPORATE/models.py
from django.db import models
from IT_ADMIN.models import BaseModel
from HR.models import Employee
from IT_ADMIN.models import Service
# Create your models here.


class Notifications(BaseModel):
    title = models.CharField(max_length=60)
    description = models.TextField(max_length=300)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Notification'
        verbose_name_plural = 'Notifications'


READ_STATUS = (("read", "read"),
               ("unread", "unread"),
               )


class Mark_as_read(BaseModel):
    Notification = models.ForeignKey(Notifications, on_delete=models.CASCADE)
    read_status = models.CharField(max_length=8, choices=READ_STATUS)
    recipient = models.ManyToManyField(Employee)


UNIT_CHOICES = (("per day", "per day"), ("per usage",
                "per usage"), ("per hour", "per hour"))


class Service_payment(BaseModel):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    unit = models.CharField(
        max_length=20, default='running', choices=UNIT_CHOICES)
    amount = models.FloatField()

    def __str__(self):
        return self.service.service_name
    class Meta:
        verbose_name = 'Service payment'
        verbose_name_plural = 'Service payments'

travlounge/IT_ADMIN/models.py
from email.mime import image
from django.utils import timezone
import datetime
from django.db import models
from django.contrib.auth.models import Group, User
from django.db.models.deletion import SET_NULL
from django.utils.translation import ugettext_lazy as _
import cloudinary
from cloudinary.models import CloudinaryField
from django.core.validators import FileExtensionValidator
from django.utils import timezone
from django.db.models.signals import pre_save, post_save, post_delete
import requests
import json
from django.core import serializers
from django.forms.models import model_to_dict

# from HR.models import Employee

# Create your models here.
# ----------------------------Rename Groups as Roles---------------------


class Role(Group):
    class Meta:
        proxy = True
        app_label = 'auth'
        verbose_name = _('Role')
# -----------------------------basemodel-------------------------------------------------------------------------------------------------------------


class BaseModel(models.Model):
    """Model for subclassing."""
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True
        ordering = ['-created_on']
# --------------------IT ADMIN----------------------------------

TYPE = (("s","sleeping pod"),
                 ("t","toloo"),
                 ("cw","carwash"),
                 ("ec","e-charge"),
                 ("c","coffee"),
                 ("m","minimart"))

class Service(BaseModel):  # create new service (example: Toloo)@@@@
    service_name = models.CharField(max_length=60)
    type= models.CharField(max_length=60,choices=TYPE, unique=True)
    description = models.TextField(max_length=500)
    act_as_service = models.BooleanField(default=True)
    logo = CloudinaryField('images/service')

    def __str__(self):
        return self.service_name


def service_post_save(sender, created, instance, *args, **kwargs):
    logo = str(instance.logo)
    logo = logo.replace("http", "https")

    headers = {"Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjEzNzUwOTIwMDA1LCJpYXQiOjE2NTQ5MjAwMDUsIm1vYmlsZSI6IjExMjIzMzQ0NTUifQ.AmsZIvdFsld_KzvufGMiB2YtdE67ezjnFOYFdVvZtqU"}
    if created:
        r = requests.post('http://128.199.139.248:6969/createService',
                          data=json.dumps({
                              "id": instance.id,
                              "service_name": instance.service_name,
                              "type": instance.type,
                              "logo": logo,
                              "description": instance.description,
                              "act_as_service": instance.act_as_service
                          }),headers=headers)
    else:
        r = requests.put(f'http://128.199.139.248:6969/getServiceById/{instance.id}',
                         data=json.dumps({
                             "id": instance.id,
                             "service_name": instance.service_name,
                             "type": instance.type,
                             "logo": logo,
                             "description": instance.description,
                             "act_as_service": instance.act_as_service,
                             "is_deleted": instance.is_deleted,
                         }),headers=headers)


post_save.connect(service_post_save, sender=Service)


class Service_type(BaseModel):  # create new service type (example: TL4x4 )
    service_type = models.CharField(max_length=60)
    service_name = models.ForeignKey(
        Service, on_delete=models.CASCADE, null=True)
    act_as_service = models.BooleanField(default=True)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.service_type

    class Meta:
        verbose_name_plural = 'Service types'
        verbose_name = 'New Service type'


def service_type_post_save(sender, created, instance, *args, **kwargs):
    print(instance.service_name,"jjjjjjjjjjjjjjjjjjjjjjjjjjj")
    headers = {"Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjEzNzUwOTIwMDA1LCJpYXQiOjE2NTQ5MjAwMDUsIm1vYmlsZSI6IjExMjIzMzQ0NTUifQ.AmsZIvdFsld_KzvufGMiB2YtdE67ezjnFOYFdVvZtqU"}
    if created:
        r = requests.post('http://128.199.139.248:6969/createServiceType',
                          data=json.dumps({
                              "id": instance.id,
                              "service_id": instance.service_name.id,
                              "type": instance.service_type,
                              "count": instance.count,
                              "act_as_service": instance.act_as_service
                          }),headers=headers)
    else:
        r = requests.put(f'http://128.199.139.248:6969/getServiceTypeById/{instance.id}',
                         data=json.dumps({
                             "id": instance.id,
                             "service_id": instance.service_name.id,
                             "type": instance.service_type,
                             "count": instance.count,
                             "act_as_service": instance.act_as_service,
                             "is_deleted": instance.is_deleted
                         }),headers=headers)


post_save.connect(service_type_post_save, sender=Service_type)


class Service_to_role(BaseModel):  # Mapping roles to service types
    service_type = models.ForeignKey(
        Service_type, on_delete=models.CASCADE, null=True)
    role = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
    no_of_role = models.PositiveIntegerField()

    def __str__(self):
        return str(self.role)


# ---------------CREATE WAREHOUSE---------------------
SIZE_CHOICES = (("small", "small"), ("medium", "medium"), ("large", "large"),)
# class Warehouse_details(BaseModel):
#     name = models.CharField(max_length=50)
#     size = models.CharField(max_length=20, choices=SIZE_CHOICES)
#     address = models.TextField(max_length=300)
#     cash = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
#     def __str__(self):
#         return self.name
# ---------------CREATE FACILITY---------------------
STATUS_CHOICES = (("running", "running"),
                  ("stopped", "stopped"),
                  ("pending", "pending"),
                  ("initiated", "initiated"),)


class Facility(BaseModel):
    facility_name = models.CharField(max_length=60)
    state = models.CharField(max_length=60)
    District = models.CharField(max_length=60)
    pincode = models.CharField(max_length=60)
    longitude = models.CharField(max_length=60)
    latitude = models.CharField(max_length=60)
    # Pending or Initialised or running or stopped
    facility_status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default='pending')
    Address = models.TextField(max_length=300)
    # warehouse = models.ManyToManyField(Warehouse_details)
    sts = models.BooleanField(default=False)

    def __str__(self):
        return self.facility_name + " : "+self.facility_status

    class Meta:
        verbose_name_plural = 'Facilities'
        verbose_name = 'New Facility'

def facility_post_save(sender, created, instance, *args, **kwargs):
    print("kkkkkkkkkkkkkkkkkkkkkkkkkkkk")
    headers = {"Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjEzNzUwOTIwMDA1LCJpYXQiOjE2NTQ5MjAwMDUsIm1vYmlsZSI6IjExMjIzMzQ0NTUifQ.AmsZIvdFsld_KzvufGMiB2YtdE67ezjnFOYFdVvZtqU"}
    if created:
        print("createdddddddddddddddddddddddddddddd")
        r = requests.post('http://128.199.139.248:6969/createFacilities',
                          data=json.dumps({
                              "id": instance.id,
                              "name": instance.facility_name,
                              "state": instance.state,
                              "district": instance.District,
                              "pincode": instance.pincode,
                              "longitude": instance.longitude,
                              "latitude": instance.latitude,
                              "facility_status": instance.facility_status,
                              "address": instance.Address,
                          }),headers=headers)
    else:
        print("puttttttttttttttttttttttttttttt")
        r = requests.put(f'http://128.199.139.248:6969/getFacilityById/{instance.id}',
                         data=json.dumps({
                             "id": instance.id,
                             "name": instance.facility_name,
                             "state": instance.state,
                             "district": instance.District,
                             "pincode": instance.pincode,
                             "longitude": instance.longitude,
                             "latitude": instance.latitude,
                             "facility_status": instance.facility_status,
                             "address": instance.Address,
                             "is_deleted": instance.is_deleted,
                         }),headers=headers)


post_save.connect(facility_post_save, sender=Facility)



# ------------------------------------------------------FacilitySleepingPod------------------------------------------------------------


STATUS = (
    ("stopped", "stopped"),
    ("running", "running")
)
class Facility_to_service(BaseModel):  # Mapping A facility to service type
    service_type = models.ForeignKey(
        Service_type, on_delete=models.CASCADE, null=True,verbose_name="service")
    facility = models.ForeignKey(Facility, on_delete=models.CASCADE, null=True)
    gstin = models.CharField(max_length=60)
    status = models.CharField(max_length=20, default='running', choices=STATUS)

    def __str__(self):
        return self.facility.facility_name + " - " + self.service_type.service_type

    class Meta:

travlounge/IT_ADMIN/forms.py
from dataclasses import field
from django import forms
from IT_ADMIN .models import Facility_docs, Service, Banner, Service_type
from IT_ADMIN .models import Carwash, Facility_docs, Service, Banner


def validate_file_extension(value):
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.pdf']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Only PDF are allowded.')


def validate_image_extension(value):
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.jpeg', 'png']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Unsupported file extension.')


class CouplingUploadForm(forms.ModelForm):

    docs = forms.FileField(label=' File Upload:',
                           required=True, validators=[validate_file_extension])

    class Meta:
        model = Facility_docs
        fields = '__all__'


class service_logo_Form(forms.ModelForm):
    logo = forms.ImageField()
    logo_image_id = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        model = Service
        fields = "__all__"
        widgets = {'logo_image_id': forms.Textarea}

    def __init__(self, *args, **kwargs):
        super(service_logo_Form, self).__init__(*args, **kwargs)
        self.fields['logo'].required = False
        self.fields['logo_image_id'].required = False
        self.fields['logo_image_id'].label = ""


class Banner_Form(forms.ModelForm):
    photo = forms.ImageField()
    banner_image_id = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        model = Banner
        fields = "__all__"
        widgets = {'banner_image_id': forms.Textarea}

    def __init__(self, *args, **kwargs):
        super(Banner_Form, self).__init__(*args, **kwargs)
        self.fields['photo'].required = False
        self.fields['banner_image_id'].required = False
        self.fields['banner_image_id'].label = ""


class vehicle_Form(forms.ModelForm):
    image = forms.ImageField()
    vehicle_image_id = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        model = Carwash
        fields = "__all__"
        widgets = {'vehicle_image_id': forms.Textarea}

    def __init__(self, *args, **kwargs):
        super(vehicle_Form, self).__init__(*args, **kwargs)
        self.fields['image'].required = False
        self.fields['vehicle_image_id'].required = False
        self.fields['vehicle_image_id'].label = ""


class speciality_Form(forms.ModelForm):
    image = forms.ImageField()
    speciality_image_id = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        model = Carwash
        fields = "__all__"
        widgets = {'speciality_image_id': forms.Textarea}

    def __init__(self, *args, **kwargs):
        super(speciality_Form, self).__init__(*args, **kwargs)
        self.fields['image'].required = False
        self.fields['speciality_image_id'].required = False
        self.fields['speciality_image_id'].label = ""


class CouplingUploadForm3(forms.ModelForm):

    docs = forms.FileField(label=' File Upload:',
                           required=True, validators=[validate_file_extension])

    class Meta:
        model = Facility_docs
        fields = '__all__'


class ProductForm(forms.ModelForm):
    @staticmethod
    def parse_filter_kwargs(**kwargs):
        if 'initial' in kwargs:
            if u'_changelist_filters' in kwargs['initial']:
                filters = kwargs['initial'].pop('_changelist_filters')
                for key, value in [p.split('=') for p in filters.split('&')]:
                    kwargs['initial'][key] = value
        return kwargs

    def __init__(self, *args, **kwargs):
        kwargs = self.parse_filter_kwargs(**kwargs)
        super(ProductForm, self).__init__(*args, **kwargs)


# class servicetype_form(forms.ModelForm):

#     image_id = forms.CharField()

#     class Meta:
#         model = Service_type
#         fields = "__all__"

#     def __init__(self, *args, **kwargs):
#         super(servicetype_form, self).__init__(*args, **kwargs)
#         self.fields['image_id'].required = False

travlounge/IT_ADMIN/views.py
from django.shortcuts import render
from django.http import HttpResponse
from IT_ADMIN .models import token_get
from django.contrib.auth.models import Group,User
# Create your views here.
def preview(request):
    token=request.POST.get('data')
    current_user = request.user
    user_id=current_user.id
    if token_get.objects.filter(user=user_id).exists():
        print("llllllllllllllllllllllllllllllllllllllllllllllllll")
        token_user = token_get.objects.get(user=user_id)
        print("kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk")
        token_user.token_get = token
        print(token,"llllllllllllllllllllllllllllllllllhhhhhhhhhhhhhhhhhhhhyyyy")
        token_user.save()
    else:
        user_obj = User.objects.get(id=user_id)
        print("00000000000000000000000000000000000000000")
        token_user = token_get(user=user_obj,token_get=token)
        token_user.save()
    return HttpResponse('heloo')


# def imgViewFunction(request):
#     # request.GET.get('')
#     id=150
    
#     print("ooooooooooooooooooooooooooo............ooooooooooooooooooooooooo")
#     return HttpResponse("ooooo")

travlounge/IT_ADMIN/templates/change_form.html
{% extends "admin/change_form.html" %}
{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
{% include inline_admin_formset.opts.template %}
{% endfor %}
  <fieldset class="module">
  <input type="submit" value="Approve" name="apply">
</fieldset>


{% endblock %}

travlounge/IT_ADMIN/templates/logo.html
{% extends "admin/change_form.html" %}


{% block after_field_sets %}{{ block.super }}
{% load static %}

<link rel="stylesheet" href="{% static 'css/admin/singlecrop.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/cropper/2.3.4/cropper.min.css'><link rel="stylesheet" href="./style.css">

<!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-vk5WoKIaW/vJyUAd9n/wmopsmNhiy+L2Z+SBxGYnUkunIxVxAv/UtMOhba/xskxh" crossorigin="anonymous"></script> -->
{% for item in original.items_set.all %} {{ item }} {% endfor %}
{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
{% include inline_admin_formset.opts.template %}
{% endfor %}





{% block submit_buttons_bottom %}
<div class="submit-row">
<input type="submit" value="save" name="_save_btn" class="save_btn" onclick="functiontest()"/>
</div>
{% endblock %}




  <img class="cropped" src="{{logo_img.logo}}" >
  <div class="box-2 img-result hide">
    <!-- <img class="cropped" src="" alt="" > -->
  </div>
  <main class="page">

    <!-- leftbox -->
    <div class="box-2">
      <div class="result"></div>
    </div>

    <!-- input file -->
    <div class="box">
      <div class="options hide">
        <input type="number" class="img-w" value="300" min="100" max="1200" hidden/>
      </div>
      <!-- save btn -->
      <button class="btn save hide">crop</button>
      <button class="btn cancel hide" type="button" onclick="cancelclick()">Cancel</button>
      
    </div>
  </main>
 <script>

function cancelclick(){
  
  $(".page").css('display','none');
  changedImage=false;

}

$("#service_form").prepend('<p  class="errornote" id="please_crop" hidden>please select and crop image</p>') 
$("#service_form").prepend('<p  class="errornote" id="please_cancel" hidden>Crop image or cancel</p>') 
$("#service_form").prepend('<p  class="errornote" id="all_fields" hidden>please fill all fields</p>') 



 $('.submit-row').hide()
 function functiontest(){
  document.getElementById("id_logo").value = "";
  event.preventDefault();
  cropped = document.querySelector('.cropped')


  var service_name=$('#id_service_name').val()
   var description=$('#id_description').val()
   if (($(".cropped").attr('src')==''&& (service_name == '' || description=='' ))||($(".cropped").attr('src') !==''&& (service_name == '' || description=='' ))){

  //  if ($(".cropped").attr('src')=='' && (service_name == '' || description=='' )){
 
 $("#all_fields").css('display','block');
}
else if($(".cropped").attr('src')==''&& (service_name !== '' && description !=='' )){
$("#please_crop").css('display','block');
}
else if(changedImage==true){
$("#please_cancel").css('display','block');
}

else{
$('#service_form').submit()
}

  // ######################################################################################################################
  // if ($(".cropped").attr('src')==''){
  //   alert("please crop image")

  // }
  // else if(changedImage==true){
  //   $("#service_form").prepend('<p  class="errornote">Crop image or cancel</p>') 
  //   // alert("Crop image or cancel")
  //  }
  // else{
  //   $('#service_form').submit()
  // }

  // ##########################################################################################################################
 }
//  $(".save_btn").click(function() {
//   alert( "Handler for .click() called." );
// });
  

 </script>

    
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/cropperjs/0.8.1/cropper.min.js'></script>
<script>
var changedImage;
// vars
let result = document.querySelector('.result'),
img_result = document.querySelector('.img-result'),
img_w = document.querySelector('.img-w'),
img_h = document.querySelector('.img-h'),
options = document.querySelector('.options'),
save = document.querySelector('.save'),
cancel = document.querySelector('.cancel'),
cropped = document.querySelector('.cropped'),
dwn = document.querySelector('.download'),
upload = document.querySelector('#id_logo'),
cropper = '';

// on change show image with crop options
upload.addEventListener('change', e => {
  
  $(".page").css('display','block');
  changedImage=true;
  
  if (e.target.files.length) {
    const format_lst=['jpg','jpeg','png','PNG','JPEG','JPG']
    var nh= e.target.files[0]['name'].split('.').pop()

if (format_lst.includes(nh)== false){
 $("#service_form").prepend('<p  class="errornote">Unsupported file extension, supported formates(jpg,jpeg,png.) </p>') 
  // alert("Unsupported file extension, supported formates(jpg,jpeg,png.)")

}

else{
    // start file reader
    const reader = new FileReader();
    reader.onload = e => {
      if (e.target.result) {
        // create new image
        let img = document.createElement('img');
        img.id = 'image';
        img.src = e.target.result;
        // clean result before
        // result.innerHTML = '';
        // append new image
        result.innerHTML = '';
        result.appendChild(img);
        // show save btn and options
        save.classList.remove('hide');
        cancel.classList.remove('hide');
        options.classList.remove('hide');
        // init cropper
        cropper = new Cropper(img,{
          dragMode: 'move',
         
    // autoCropArea: 10,
    restore: false,
    guides: false,
    center: false,
    highlight: false,
    cropBoxMovable: true,
    cropBoxResizable: false,
    toggleDragModeOnDblclick: false,
    movable: false,
        });
        

      }
      
    };
    
    reader.readAsDataURL(e.target.files[0]);
  }
}
  
});


// save on click
save.addEventListener('click', e => {
  document.getElementById('id_logo_image_id').value = '';
  changedImage=false;
  e.preventDefault();
  // get result to data uri
  let imgSrc = cropper.getCroppedCanvas({
    aspectRatio: 1 / 1, // select area ratio 16:9, 4:3, 1:1, 2:3, free
    viewMode: 3, // sketch image to fit the container
    
    
    
    width: img_w.value // input value
  }).toDataURL();
  // remove hide class of img
  cropped.classList.remove('hide');
  img_result.classList.remove('hide');
  // show image cropped
  cropped.src = imgSrc;
  document.getElementById('id_logo_image_id').value = imgSrc;
  dwn.classList.remove('hide');
  dwn.download = 'imagename.png';
  dwn.setAttribute('href', imgSrc);
});


</script>



<script>
    $('#id_service_name').on('change', function(){
     var init_value =$(this).val();
  console.log(init_value)
  $.ajax({
  type: 'GET',
  url: '/admin/IT_ADMIN/service/add/',
  data: {'data':init_value

  },
  cache: false,
  success: function(result) {
     console.log(result)
     if(result.status == 200){
          document.getElementById("id_service_name").value = '';
          alert('This service is already created')
          

     }

    
     
    
  }
});

});
 

</script>


{% endblock %}

travlounge/IT_ADMIN/templates/speciality.html
{% extends "admin/change_form.html" %}


{% block after_field_sets %}{{ block.super }}
{% load static %}


<link rel="stylesheet" href="{% static 'css/admin/singlecrop.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/cropper/2.3.4/cropper.min.css'><link rel="stylesheet" href="./style.css">

{% for item in original.items_set.all %} {{ item }} {% endfor %}
{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
{% include inline_admin_formset.opts.template %}
{% endfor %}


<img class="cropped" src="{{speciality_img.image}}">
<div class="box-2 img-result hide">
  <img class="cropped" src="" alt="">
</div>
<main class="page">

	<!-- leftbox -->
	<div class="box-2">
		<div class="result"></div>
	</div>

	<!-- input file -->
	<div class="box">
		<div class="options hide">
			<input type="number" class="img-w" value="300" min="100" max="1200" hidden/>
		</div>
		<!-- save btn -->
		<button class="btn save hide">crop</button>
    <button class="btn cancel hide" type="button" onclick="cancelclick()">Cancel</button>
		
	</div>
</main>
 
{% block submit_buttons_bottom %}
<div class="submit-row">
<input type="submit" value="save" name="_save_btn" class="save_btn" onclick="functionspeciality()"/>
</div>
{% endblock %}

<script>

function cancelclick(){
  
  $(".page").css('display','none');
  changedImage=false;
  $("#id_image").val('');
}
$("#speciality_form").prepend('<p  class="errornote" id="please_crop" hidden>please select and crop image</p>') 
$("#speciality_form").prepend('<p  class="errornote" id="please_cancel" hidden>Crop image or cancel</p>') 
$("#speciality_form").prepend('<p  class="errornote" id="all_fields" hidden>please fill all fields</p>') 

  $('.submit-row').hide()
  function functionspeciality(){
document.getElementById("id_image").value = "";
   event.preventDefault();
   cropped = document.querySelector('.cropped')
   var title=$('#id_title').val()
   var description=$('#id_description').val()
   if (($(".cropped").attr('src')==''&& (title == '' || description=='' ))||($(".cropped").attr('src') !==''&& (title == '' || description=='' ))){

  //  if ($(".cropped").attr('src')=='' && (title == '' || description=='' )){
 
 $("#all_fields").css('display','block');
}
else if($(".cropped").attr('src')==''&& (title !== '' && description !=='' )){
$("#please_crop").css('display','block');
}
else if(changedImage==true){
$("#please_cancel").css('display','block');
}

else{
$('#speciality_form').submit()
}
// #################################################################################################################
  //  if ($(".cropped").attr('src')==''){
  //   $("#speciality_form").prepend('<p  class="errornote">please crop image</p>') 
 
  //  }
  //  else if(changedImage==true){
  //   $("#speciality_form").prepend('<p  class="errornote">Crop image or cancel</p>') 
  //  }
  //  else{
  //    $('#speciality_form').submit()
  //  }


// ##############################################################################################################################

  }

 
  </script>
  
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/cropperjs/0.8.1/cropper.min.js'></script>
<script>
var changedImage;
// vars
let result = document.querySelector('.result'),
img_result = document.querySelector('.img-result'),
img_w = document.querySelector('.img-w'),
img_h = document.querySelector('.img-h'),
options = document.querySelector('.options'),
save = document.querySelector('.save'),
cancel = document.querySelector('.cancel'),
cropped = document.querySelector('.cropped'),
dwn = document.querySelector('.download'),
upload = document.querySelector('#id_image'),
cropper = '';

// on change show image with crop options
upload.addEventListener('change', e => {
  $(".page").css('display','block');
  changedImage=true;
  
  if (e.target.files.length) {
    // start file reader

    const format_lst=['jpg','jpeg','png','PNG','JPEG','JPG']
  var nh= e.target.files[0]['name'].split('.').pop()

if (format_lst.includes(nh)== false){
  $("#speciality_form").prepend('<p  class="errornote">Unsupported file extension, supported formates(jpg,jpeg,png.) </p>') 
}


else{
    const reader = new FileReader();
    reader.onload = e => {
      if (e.target.result) {
        // create new image
        let img = document.createElement('img');
        img.id = 'image';
        img.src = e.target.result;
        result.innerHTML = '';
        result.appendChild(img);
        // show save btn and options
        save.classList.remove('hide');
        cancel.classList.remove('hide');
        options.classList.remove('hide');
        // init cropper
        cropper = new Cropper(img,{
          dragMode: 'move',
    restore: false,
    guides: false,
    center: false,
    highlight: false,
    cropBoxMovable: false,
    cropBoxResizable: false,
    toggleDragModeOnDblclick: false,
    // data:{ //define cropbox size
    //   width: 2400,
    //   height:  200,
    // },
        });
      }
    };
    reader.readAsDataURL(e.target.files[0]);
  }
}
});

// save on click
save.addEventListener('click', e => {
document.getElementById('id_speciality_image_id').value = '';
changedImage=false;
  e.preventDefault();
  // get result to data uri
  let imgSrc = cropper.getCroppedCanvas({
    width: img_w.value // input value
  }).toDataURL();
  // remove hide class of img
  cropped.classList.remove('hide');
  img_result.classList.remove('hide');
  // show image cropped
  cropped.src = imgSrc;
  document.getElementById('id_speciality_image_id').value = imgSrc;
  dwn.classList.remove('hide');
  dwn.download = 'imagename.png';
  dwn.setAttribute('href', imgSrc);
});


</script>



{% endblock %}