travlounge/Travlounge/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from IT_ADMIN import views
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path('token/', views.preview, name='tocken'),
    path('admin/', admin.site.urls),
    
    path('summernote/', include('django_summernote.urls')),
    path('firebase-messaging-sw.js', (TemplateView.as_view(template_name="firebase-messaging-sw.js",
         content_type='application/javascript')), name='sw.js'),
]

admin.site.site_title = 'Travlounge'
admin.site.index_title = 'Manage facilities'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

travlounge/AUDIT/models.py
from urllib import response
from django.contrib import messages
from django.db import models
from IT_ADMIN.models import Facility, BaseModel, Facility_to_service
import cloudinary
from cloudinary.models import CloudinaryField
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User, Group
from django.core.validators import FileExtensionValidator
import datetime
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

# Create your models


AUDIT_STATUS_CHOICES = (
    ("Awaiting", "Awaiting"),
    ("In Progress", "In Progress"),
    ("finished", "finished")
)


class Audit_headings(BaseModel):
    heading = models.CharField(max_length=50)

    def __str__(self):
        return self.heading

    class Meta:
        verbose_name = ' Audit Questions'
        verbose_name_plural = ' Make Audit Questions'


class Audit_questions(BaseModel):
    heading_id = models.ForeignKey(Audit_headings, on_delete=models.CASCADE)
    questions = models.CharField(max_length=50)
    instructions = models.CharField(max_length=50)

    def __str__(self):
        return str('')

    class Meta:
        verbose_name = ' Audit Question'
        verbose_name_plural = ' Audit Questions'


class Auditor_information(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.CharField(max_length=50)
    auditor_name = models.CharField(max_length=50)
    highest_position = models.CharField(max_length=50)
    email_regex = RegexValidator(regex=r'^[A-Za-z0-9]+@[a-z]+\.[a-z]{2,3}$', message='Email must be entered in the correct format ( eg. mail@example.com )')
    email = models.CharField(validators=[email_regex], max_length=50)
    phone_regex = RegexValidator(regex=r'^(\+[9][1])?(\+[9][1]\s)?\d{10}$', message="Phone number must be entered in the correct format (Either +91xxxxxxxxxx or xxxxxxxxxxx)")
    contact_number1 = models.CharField(validators=[phone_regex], max_length=17)
    contact_number2 = models.CharField(validators=[phone_regex], max_length=50)

    

    class Meta:
        verbose_name = 'New auditor'
        verbose_name_plural = 'Add auditors'

    def __str__(self):
        return self.auditor_name

    def save(self, *args, **kwargs):
        self.user.is_staff = True
        self.user.is_active = True
        self.user.email = self.email
        self.user.save()
        super(Auditor_information, self).save(*args, **kwargs)



SCORE_CHOICES = (
    ("pass", "pass"),
    ("fail", "fail"))


class Audit_schedule(BaseModel):
    audit_type = models.CharField(max_length=50)
    audit_title = models.CharField(max_length=50,)
    start_datetime = models.DateTimeField(help_text="Format: YYYY-MM-DD <br/> &emsp;&emsp;&emsp;&emsp; HH:MM:SS")
    end_datetime = models.DateTimeField(help_text="Format: YYYY-MM-DD <br/> &emsp;&emsp;&emsp;&emsp; HH:MM:SS")
    facility_id = models.ForeignKey(
        Facility, on_delete=models.CASCADE, verbose_name='Select facility')
    service_id = models.ForeignKey(
        Facility_to_service, on_delete=models.CASCADE, null=True, verbose_name='Select service')
    auditor = models.ForeignKey(
        Auditor_information, on_delete=models.CASCADE, related_name="auditor")
    score = models.CharField(max_length=50, choices=SCORE_CHOICES)
    heading_id = models.ForeignKey(
        Audit_headings, on_delete=models.CASCADE, verbose_name='Select Questions')
    status = models.CharField(
        max_length=200, default="Awaiting", choices=AUDIT_STATUS_CHOICES)
    justification_flag = models.BooleanField(max_length=200, default=False)


    class Meta:
        verbose_name = 'A New Scheduled Audit'
        verbose_name_plural = 'Schedule an Audit'

    def __str__(self):
        return self.audit_title

    def facility_id_link(self):
        return self.facility_id

    # def save(self, *args, **kwargs):
    #     print(self.start_datetime.replace(tzinfo=None),'101010',datetime.datetime.now())
    #     if self.start_datetime.replace(tzinfo=None) < datetime.datetime.now():
    #         raise ValidationError("The date cannot be in the past!")
    #     if self.end_datetime.replace(tzinfo=None) < self.start_datetime.replace(tzinfo=None):
    #         raise ValidationError("The date cannot be lesser than starting time!")
    #     super(Audit_schedule, self).save(*args, **kwargs)
    
    def is_past(self):
        if self.start_datetime.replace(tzinfo=None) < datetime.datetime.now():
            resul=None
            return resul
        else:
            resul=1
            return resul
    def is_lesser(self):
        if self.end_datetime.replace(tzinfo=None) < self.start_datetime.replace(tzinfo=None):
            result=None
            return result
        else:
            result=1
            return result

    def clean(self):
        print(self.id,'\n\n\n\n\n\n')
        if self.id==None:
            if not self.start_datetime==None:
                if not self.is_past():
                    raise ValidationError('Starting DateTime cannot be in the past!')
                if not self.is_lesser():
                    raise ValidationError('Ending time/date cannot be lesser than starting!')

    facility_id_link.short_description = "facility"
    facility_id_link.allow_tags = True


JUSTIFICATION_CHOICES = (
    ("cleared", "cleared"),
    ("pending", "pending"))


class Audit_issues(BaseModel):
    issues = models.CharField(max_length=50)
    description = models.TextField(max_length=50)
    justification = models.CharField(max_length=50)
    status = models.CharField(
        max_length=200, default="pending", choices=JUSTIFICATION_CHOICES)
    audit_no = models.ForeignKey(
        Audit_schedule, on_delete=models.CASCADE, related_name="auditnum", verbose_name='Audit')
    justification_status = models.CharField(
        max_length=100, default="pending", choices=JUSTIFICATION_CHOICES)

    def __str__(self):
        return self.issues

    class Meta:
        verbose_name = 'Issues'
        verbose_name_plural = 'Issues'


class Audit_info(BaseModel):
    audit_no = models.ForeignKey(
        Audit_schedule, on_delete=models.CASCADE, verbose_name='Audit')
    auditor_id = models.ForeignKey(
        Auditor_information, on_delete=models.CASCADE, verbose_name='Auditor')
    audit_start_datetime = models.DateTimeField(null=True, blank=True)
    audit_end_datetime = models.DateTimeField(null=True, blank=True)


class Audit_performance_analysis_report(BaseModel):
    audit_no = models.ForeignKey(
        Audit_schedule, on_delete=models.CASCADE, null=True, verbose_name='Audit')
    auditor_id = models.ForeignKey(
        Auditor_information, on_delete=models.CASCADE, null=True, verbose_name='Auditor')
    comments = models.CharField(max_length=200, null=True)
    honesty = models.IntegerField(null=True)
    work_quality = models.IntegerField(null=True)
    punctality = models.IntegerField(null=True,  verbose_name='punctuality')
    attitude = models.IntegerField(null=True)

    def __str__(self):
        return str(self.auditor_id)

    class Meta:
        verbose_name = 'Auditor analysis'
        verbose_name_plural = 'Auditor analysis'


class Audit_star_classification(BaseModel):
    audit_no = models.ForeignKey(
        Audit_schedule, on_delete=models.CASCADE, verbose_name='Audit')
    facility_id = models.ForeignKey(
        Facility, on_delete=models.CASCADE, verbose_name='Facility')
    service = models.ForeignKey(
        Facility_to_service, on_delete=models.CASCADE, null=True)
    star = models.IntegerField()

    class Meta:
        verbose_name = 'Audit rating'
        verbose_name_plural = 'Audit rating'

    def __str__(self):
        return str(self.audit_no.audit_title)


class Auditshedule_docs(BaseModel):
    
    # def validate_file_size(value):
    #     print('hello\n\n')
    #     filesize= value.size
    #     if filesize > 10485760:
    #         raise ValidationError("You cannot upload file more than 10Mb")
    #     else:
    #         return value

    Audit_schedule = models.ForeignKey(
        Audit_schedule, on_delete=models.CASCADE, related_name="doc", verbose_name='Audit')
    doc_name = models.CharField(
        max_length=60, null=True, verbose_name='Document Name  (document should in pdf format)')
    docs = CloudinaryField('Docs/Audit_schedule_docs',help_text='Upload document in pdf format')

    def __str__(self):
        return self.doc_name

    def clean(self):
        if self.id==None:
            extensions=('.pdf', '.doc', '.docx',
                        '.ods', '.xls', '.xlsm', '.xlsx')
            if not self.docs.name.endswith(extensions):
                raise ValidationError("File should be in pdf, doc, docx, xls, xlsx or ods format")
            size=self.docs.size
            if size>10485760:
                raise ValidationError("You cannot upload file more than 10MB")
            else:
                pass
        else:
            pass
        


class Auditshedule_return_docs(BaseModel):
    Audit_schedule = models.ForeignKey(
        Audit_schedule, on_delete=models.CASCADE, verbose_name='Audit')
    doc_name = models.CharField(
        max_length=60, null=True, verbose_name='Document Name(document should in pdf format)')
    docs = CloudinaryField('Docs/Audit_schedule_return_docs', help_text="Upload a pdf file with one or more identity details inside")

    class Meta:
        verbose_name = 'Return document'
        verbose_name_plural = 'Return documents'

    def __str__(self):
        return self.doc_name

    def clean(self):
        if self.id==None:
            extensions=('.pdf', '.doc', '.docx',
                        '.ods', '.xls', '.xlsm', '.xlsx')
            if not self.docs.name.endswith(extensions):
                raise ValidationError("File should be in pdf, doc, docx, xls, xlsx or ods format")
            size=self.docs.size
            if size>10485760:

travlounge/AUDIT/forms.py
from dataclasses import field, fields
from django import forms
from django.forms import ModelForm
from django.db.models.manager import Manager
from AUDIT .models import Audit_info, Auditor_information, Audit_schedule, Audit_headings, Audit_questions, Auditshedule_docs, Audit_answers_saved, Audit_issues, Audit_implimentations, Auditshedule_return_docs, Audit_star_classification, Audit_performance_analysis_report
from django.core.exceptions import ValidationError
import os


# def validate_file_extension(value):
#     ext = os.path.splitext(value.name)[1]
#     valid_extensions = ['.pdf', '.doc', '. docx',
#                         '.ods', '.xls', '.xlsm', '.xlsx']
#     if not ext.lower() in valid_extensions:
#         raise ValidationError(u'Unsupported file extension.')


class CouplingUploadForm(forms.ModelForm):

    docs = forms.FileField(label=' File Upload:',
                           required=True,
                            # validators=[validate_file_extension],
                           help_text='Upload document in pdf format')

    class Meta:
        model = Auditshedule_docs
        exclude = ['doc_name']

travlounge/AUDIT/views.py
from django.shortcuts import render

# Create your views here.

travlounge/AUDIT/templates/change_form52.html
{% extends "admin/change_form.html" %}
{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
{% include inline_admin_formset.opts.template %}
{% endfor %}
<fieldset class="=model">
  <form method="POST"></form>
  <div class="append"></div>
  </select>
  <input type="submit">
  </form>
</fieldset>

<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert-dev.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">
<script>
  $(document).ready(function () {
    $('#id_audit_title').on('change', function () {
      var init_value = $(this).val();
      console.log(init_value)
      $.ajax({
        type: 'GET',
        url: '/admin/AUDIT/audit_schedule/add/',
        data: {
          'data': init_value

        },
        cache: false,
        success: function (result) {
          if (result.status == 200) {
            document.getElementById("id_audit_title").value = '';
            swal("Oops", "This audit is already created!", "error");

          }




        }
      });

    });

    $("select#id_facility_id").change(function () {
      var selectedCountry = $(this).val();
      $.ajax({
        method: "GET",
        url: "/admin/AUDIT/audit_schedule/add/",
        data: {
          'offset_limit': selectedCountry,

        },
        success: function (response) {
          $("#id_service_id").empty();

          let data = '';

          var count = Object.keys(response).length;
          $.each(response, function (key, value) {
            data += `<option value=${key}>${value}</option>`
          });

          console.log(data)
          $('#id_service_id').empty().append(data);


        }

      })


    }); zzz
  });
</script>

{% endblock %}

travlounge/AUDIT/templates/change_form53.html
{% extends "admin/change_form.html" %}
{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
{% include inline_admin_formset.opts.template %}
{% endfor %}


<div class="form-row-field-questions">


  <div>




    <div class="qustnsinstr">

      {% for i in question %}
      question:<input id="" name="question" value="{{i.questions}}" size="30" type="text" />
      instruction:<input id="" name="instruction" value="{{i.instructions}}" size="30" type="text" />
      <select name="score" id="score">
        <option value="pass">Pass</option>
        <option value="fail">fail</option>
      </select>
      <br>
      <br>
      {% endfor %}


    </div>



  </div>

</div>
<div class="form-row-field-docs">


  <div>


    <!-- <label>documents: <br></label> -->

    <div class="new">
      <H2>Documents</H2>
      {% for i in docs %}
      <BR></BR>
      <a href="https://res.cloudinary.com/beaconinfotech/image/upload/v1622022970/{{i.docs}}.pdf"> click here to
        view</a>

      {% endfor %}
      <BR></BR>
    </div>



  </div>
  <H2> Question</H2>
  <BR></BR>
</div>




<script>

  $('.form-row.field-service_id').after($('.form-row-field-questions'));
  $('.form-row-field-docs').insertAfter($('.form-row.field-service_id'));


</script>
{% endblock %}

travlounge/AUDIT/templates/change_form54.html
{% extends "admin/change_form.html" %}
{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
{% include inline_admin_formset.opts.template %}
{% endfor %}

  <fieldset class="module">
  <input type="submit" value="Reassign for justification" name="reassign">

</fieldset>

{% endblock %}

travlounge/AUDIT/templates/change_form55.html
{% extends "admin/change_form.html" %}
{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
{% include inline_admin_formset.opts.template %}
{% endfor %}

<div class="form-row-field-questions">


    <div>

        <h2>Questions asked</h2>
        <br>

        <div class="qustnsinstr">

            {% for i in question %}
            question:<input id="" name="question" value="{{i.question_id}}" size="30" type="text" />
            instruction:<input id="" name="instruction" value="{{i.instructions}}" size="30" type="text" />
            Answer: <input id="" name="answer" value="{{i.answer}}" size="15" type="text" />
            <br>
            <br>
            {% endfor %}


        </div>



    </div>

</div>


</div>
</div>
<br>
<br>
<h1>Rate the service</h1>
<span class="rating-reaction"></span>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" />
</head>

<body>
    <div class="star-rating">
        <div class="thanks-msg">Thanks for your feedback !!!</div>
        <div class="star-input">
            <input type="radio" name="rating" id="rating-5" value="5" onclick="myfunction();">
            <label for="rating-5" class="fas fa-star"></label>
            <input type="radio" name="rating" id="rating-4" value="4" onclick="myfunction();">
            <label for="rating-4" class="fas fa-star"></label>
            <input type="radio" name="rating" id="rating-3" value="3" onclick="myfunction();">
            <label for="rating-3" class="fas fa-star"></label>
            <input type="radio" name="rating" id="rating-2" value="2" onclick="myfunction();">
            <label for="rating-2" class="fas fa-star"></label>
            <input type="radio" name="rating" id="rating-1" value="1" onclick="myfunction();">
            <label for="rating-1" class="fas fa-star"></label>

            <!-- Rating Submit Form -->


        </div>
    </div>

    <div class="form-row-field-docs">


        <div>


            <!-- <label>documents: <br></label> -->

            <div class="new">
                <H2>Documents</H2>

                {% for i in redoc %}
                <BR></BR>
                <a href="https://res.cloudinary.com/beaconinfotech/image/upload/v1622022970/{{i.docs}}.pdf"> click here
                    to view</a>

                {% endfor %}
                <BR></BR>
            </div>



        </div>
    </div>
    <fieldset class="module">
        <input type="hidden" id="rating" name="actual">
        <input type="submit">
    </fieldset>
    <style>
        .star-rating form {
            display: none;
        }

        .star-rating input {
            display: none;
        }

        .star-rating {
            margin: 50px auto;
            display: table;
            width: 350px;
        }

        .star-rating label {
            padding: 10px;
            float: right;
            font-size: 44px;
            color: black;
        }

        .star-rating input:not(:checked)~label:hover,
        .star-rating input:not(:checked)~label:hover~label {
            color: #ffc107;
        }

        .star-rating input:checked~label {
            color: #ffc107;
        }

        .star-rating form .rating-reaction:before {
            width: 100%;
            float: left;
            color: #ffc107;
        }

        .star-rating input:checked~form {
            border-top: 1px solid #ddd;
            width: 100%;
            padding-top: 15px;
            margin-top: 15px;
            display: inline-block;
        }

        .star-rating form .rating-reaction {
            font-size: 24px;
            float: left;
            text-transform: capitalize;
        }

        .star-rating form .submit-rating {
            border: none;
            outline: none;
            background: #795548;
            color: #ffc107;
            font-size: 18px;
            border-radius: 4px;
            padding: 5px 15px;
            cursor: pointer;
            float: right;
        }

        form .submit-rating:hover {
            background-color: #333;
        }
    </style>

    <script>
        const btn = document.querySelector(".submit-rating");
        const thanksmsg = document.querySelector(".thanks-msg");
        const starRating = document.querySelector(".star-input");

        function myfunction() {
            for (i = 0; i < document.getElementsByName('rating').length; i++) {
                if (document.getElementsByName('rating')[i].checked == true) {
                    var ratingValue = document.getElementsByName('rating')[i].value;
                    break;
                }
            }
            document.getElementById('rating').innerHTML = ratingValue;
        }
        $('.form-row.field-auditor').after($('.form-row-field-questions'));
        $('.form-row-field-docs').insertAfter($('.form-row.field-score'));

    </script>

    <script>
        $(document).ready(function () {
            $(this).removeAttr("href");
            return false;

        });
    </script>
    {% endblock %}

travlounge/AUDIT/templates/change_form56.html
{% extends "admin/change_form.html" %}
{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}

<div class="form-row-field-rating">
            
            
    <div>
        
        <h1>Rate the service</h1>

        <div>
            <div>
                <input type="hidden" id="object_passed" name="object_passed" value={{my_extra_content}}>
                Honesty:
                1:<input type="radio" name="honesty" id="rating-5" value="1" >
               
                2:<input type="radio" name="honesty" id="rating-4" value="2">
               
                3:<input type="radio" name="honesty" id="rating-3" value="3">
                
                4:<input type="radio" name="honesty" id="rating-2" value="4">
               
                5:<input type="radio" name="honesty" id="rating-1" value="5">
              
            </div>
        </div>
        <br>
        <br>
        <div>
            <div>
                Work_quality:
                1:<input type="radio" name="rating_work" id="rating-5" value="1">
                
                2:<input type="radio" name="rating_work" id="rating-4" value="2">
               
                3:<input type="radio" name="rating_work" id="rating-3" value="3">
                
                4:<input type="radio" name="rating_work" id="rating-2" value="4">
               
                5:<input type="radio" name="rating_work" id="rating-1" value="5">
                
            </div>
        </div>
        <br>
        <br>
        <div>
            <div>
                Punctality:
                1:<input type="radio" name="rating_punctuality" id="rating-5" value="1">
                
                2:<input type="radio" name="rating_punctuality" id="rating-4" value="2">
            
                3:<input type="radio" name="rating_punctuality" id="rating-3" value="3">
                
                4:<input type="radio" name="rating_punctuality" id="rating-2" value="4">
              
                5:<input type="radio" name="rating_punctuality" id="rating-1" value="5">
               
            </div>
        </div>
        <br>
        <br>
        <div>
            <div>
                Attitude:
                1:<input type="radio" name="rating_attitude" id="rating-5" value="1">
               
                2:<input type="radio" name="rating_attitude" id="rating-4" value="2">
                
                3:<input type="radio" name="rating_attitude" id="rating-3" value="3">
               
                4:<input type="radio" name="rating_attitude" id="rating-2" value="4">
              
                5:<input type="radio" name="rating_attitude" id="rating-1" value="5">
               
            </div>
        </div>
        <fieldset>

            

           
        </fieldset>
       
            
             
                </div>
            
        
        
    </div>
  
  </div>
  
<style>
    input[type=text] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
}
</style>



<script>



 $('.form-row.field-comments').before($('.form-row-field-rating'));
</script>

{% endblock %}